version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: docker-compose-mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    networks:
      - my-network

  spring-boot-app:
    image: yosramekaoui772000/devopsproject
    container_name: app-back
    ports:
      - "8088:8089"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-compose-mysql-db:3306/devops?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - my-network

  front:
    image: yosramekaoui772000/frontproject
    ports:
      - "80:80"
    depends_on:
      - spring-boot-app
    networks:
      - mynetwork

networks:
  my-network: